stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
    url: https://hawthornephc.netlify.com
  only:
    - development
  script:
    - npm install
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
